from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from fabric import report_model, report_pages

ROOT = Path(__file__).resolve().parents[1]
ITEMS = ("SupplyResponse.Report", "SupplyResponse.SemanticModel")


def artifact_digest(root: Path) -> str:
    roots = [root / "fabric/power-bi" / item for item in ITEMS]
    roots += [root / "fabric/reporting/queries", root / "fabric/sql"]
    paths: list[Path] = []
    for directory in roots:
        if not directory.is_dir():
            raise ValueError(f"missing reporting input directory: {directory}")
        for path in (directory, *directory.rglob("*")):
            if path.is_symlink():
                raise ValueError(f"reporting input symlink: {path}")
            if path.is_file():
                paths.append(path)
    report_pages.verify(root / "fabric/power-bi/SupplyResponse.Report/definition")
    report_model.verify(
        root / "fabric/power-bi/SupplyResponse.SemanticModel/definition",
        root / "fabric/reporting/queries",
    )
    entries = [
        [
            path.relative_to(root).as_posix(),
            hashlib.sha256(path.read_bytes()).hexdigest(),
        ]
        for path in sorted(paths, key=lambda path: path.relative_to(root).as_posix())
    ]
    payload = ["supply-response-reporting-artifacts-v1", entries]
    return hashlib.sha256(
        json.dumps(payload, ensure_ascii=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def generated_module(root: Path) -> str:
    digest = artifact_digest(root)
    return (
        "# Generated by python -m fabric.report_contract; do not edit the digest.\n"
        "# This identifies local artifacts, not a deployed or available report.\n"
        'REPORTING_CONTRACT = "saved-analysis-v1"\n'
        f'REPORTING_ARTIFACT_SHA256 = "{digest}"\n'
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated_module(ROOT)
    if args.check:
        target = ROOT / "apps/api/app/_reporting_artifact.py"
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "API reporting artifact digest is stale; regenerate and review"
            )
    else:
        print(expected, end="")


if __name__ == "__main__":
    main()
