"""Create the closed-loop persistence schema

Revision ID: 0001_closed_loop_schema
Revises:
Create Date: 2026-08-31 02:46:46.127400
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_closed_loop_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_instances",
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("template_id", sa.String(length=128), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("runtime_mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "scenario_effective_time", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_case_instances")),
    )
    op.create_index(
        op.f("ix_case_instances_purpose"), "case_instances", ["purpose"], unique=False
    )
    op.create_index(
        op.f("ix_case_instances_recorded_at"),
        "case_instances",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_instances_runtime_mode"),
        "case_instances",
        ["runtime_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_instances_scenario_effective_time"),
        "case_instances",
        ["scenario_effective_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_instances_status"), "case_instances", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_case_instances_template_id"),
        "case_instances",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "analysis_versions",
        sa.Column("analysis_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("material_hash", sa.String(length=128), nullable=False),
        sa.Column("runtime_mode", sa.String(length=16), nullable=False),
        sa.Column("analysis_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "retrieval_window_ends_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_instances.case_id"],
            name=op.f("fk_analysis_versions_case_id_case_instances"),
        ),
        sa.PrimaryKeyConstraint("analysis_id", name=op.f("pk_analysis_versions")),
    )
    op.create_index(
        op.f("ix_analysis_versions_analysis_started_at"),
        "analysis_versions",
        ["analysis_started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_versions_case_id"),
        "analysis_versions",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_versions_created_at"),
        "analysis_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_versions_material_hash"),
        "analysis_versions",
        ["material_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_versions_retrieval_window_ends_at"),
        "analysis_versions",
        ["retrieval_window_ends_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_versions_runtime_mode"),
        "analysis_versions",
        ["runtime_mode"],
        unique=False,
    )
    op.create_table(
        "operational_snapshots",
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("runtime_mode", sa.String(length=16), nullable=False),
        sa.Column(
            "scenario_effective_time", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("analysis_horizon_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("analysis_horizon_end", sa.String(length=10), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_instances.case_id"],
            name=op.f("fk_operational_snapshots_case_id_case_instances"),
        ),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_operational_snapshots")),
    )
    op.create_index(
        op.f("ix_operational_snapshots_analysis_horizon_end"),
        "operational_snapshots",
        ["analysis_horizon_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_snapshots_analysis_horizon_start"),
        "operational_snapshots",
        ["analysis_horizon_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_snapshots_runtime_mode"),
        "operational_snapshots",
        ["runtime_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_snapshots_scenario_effective_time"),
        "operational_snapshots",
        ["scenario_effective_time"],
        unique=False,
    )
    op.create_table(
        "decisions",
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("analysis_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("runtime_mode", sa.String(length=16), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_versions.analysis_id"],
            name=op.f("fk_decisions_analysis_id_analysis_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_instances.case_id"],
            name=op.f("fk_decisions_case_id_case_instances"),
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_decisions")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_decisions_idempotency_key")
        ),
    )
    op.create_index(
        op.f("ix_decisions_analysis_id"), "decisions", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_decisions_case_id"), "decisions", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_decisions_decided_at"), "decisions", ["decided_at"], unique=False
    )
    op.create_index(op.f("ix_decisions_kind"), "decisions", ["kind"], unique=False)
    op.create_index(
        op.f("ix_decisions_runtime_mode"), "decisions", ["runtime_mode"], unique=False
    )
    op.create_table(
        "evidence_items",
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("analysis_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("runtime_mode", sa.String(length=16), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_versions.analysis_id"],
            name=op.f("fk_evidence_items_analysis_id_analysis_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_instances.case_id"],
            name=op.f("fk_evidence_items_case_id_case_instances"),
        ),
        sa.PrimaryKeyConstraint(
            "evidence_id", "analysis_id", name=op.f("pk_evidence_items")
        ),
    )
    op.create_index(
        op.f("ix_evidence_items_case_id"), "evidence_items", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_items_effective_at"),
        "evidence_items",
        ["effective_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_items_expires_at"),
        "evidence_items",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_items_kind"), "evidence_items", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_items_retrieved_at"),
        "evidence_items",
        ["retrieved_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_items_runtime_mode"),
        "evidence_items",
        ["runtime_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_items_source_system"),
        "evidence_items",
        ["source_system"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_items_source_timestamp"),
        "evidence_items",
        ["source_timestamp"],
        unique=False,
    )
    op.create_table(
        "approval_satisfactions",
        sa.Column(
            "approval_satisfaction_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("analysis_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=True),
        sa.Column("option_id", sa.String(length=128), nullable=False),
        sa.Column("authorization_id", sa.String(length=128), nullable=False),
        sa.Column("persona_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=128), nullable=False),
        sa.Column("satisfied", sa.Boolean(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_versions.analysis_id"],
            name=op.f("fk_approval_satisfactions_analysis_id_analysis_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_approval_satisfactions_decision_id_decisions"),
        ),
        sa.PrimaryKeyConstraint(
            "approval_satisfaction_id", name=op.f("pk_approval_satisfactions")
        ),
        sa.UniqueConstraint(
            "analysis_id",
            "decision_id",
            "option_id",
            "authorization_id",
            "persona_id",
            "role",
            name="uq_approval_satisfaction_material",
        ),
    )
    op.create_index(
        op.f("ix_approval_satisfactions_analysis_id"),
        "approval_satisfactions",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_satisfactions_authorization_id"),
        "approval_satisfactions",
        ["authorization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_satisfactions_decision_id"),
        "approval_satisfactions",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_satisfactions_option_id"),
        "approval_satisfactions",
        ["option_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_satisfactions_persona_id"),
        "approval_satisfactions",
        ["persona_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_satisfactions_role"),
        "approval_satisfactions",
        ["role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_satisfactions_satisfied"),
        "approval_satisfactions",
        ["satisfied"],
        unique=False,
    )
    op.create_table(
        "case_projection",
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("runtime_mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "scenario_effective_time", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("current_analysis_id", sa.String(length=128), nullable=True),
        sa.Column("current_analysis_hash", sa.String(length=128), nullable=True),
        sa.Column("current_decision_id", sa.String(length=128), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_instances.case_id"],
            name=op.f("fk_case_projection_case_id_case_instances"),
        ),
        sa.ForeignKeyConstraint(
            ["current_analysis_id"],
            ["analysis_versions.analysis_id"],
            name=op.f("fk_case_projection_current_analysis_id_analysis_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_case_projection_current_decision_id_decisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_case_projection")),
    )
    op.create_index(
        op.f("ix_case_projection_current_analysis_hash"),
        "case_projection",
        ["current_analysis_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_projection_current_analysis_id"),
        "case_projection",
        ["current_analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_projection_current_decision_id"),
        "case_projection",
        ["current_decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_projection_purpose"), "case_projection", ["purpose"], unique=False
    )
    op.create_index(
        "ix_case_projection_purpose_status",
        "case_projection",
        ["purpose", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_projection_runtime_mode"),
        "case_projection",
        ["runtime_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_projection_scenario_effective_time"),
        "case_projection",
        ["scenario_effective_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_projection_status"), "case_projection", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_case_projection_updated_at"),
        "case_projection",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "execution_actions",
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("action_kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_instances.case_id"],
            name=op.f("fk_execution_actions_case_id_case_instances"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_execution_actions_decision_id_decisions"),
        ),
        sa.PrimaryKeyConstraint("action_id", name=op.f("pk_execution_actions")),
    )
    op.create_index(
        op.f("ix_execution_actions_action_kind"),
        "execution_actions",
        ["action_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_actions_case_id"),
        "execution_actions",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_actions_created_at"),
        "execution_actions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_actions_decision_id"),
        "execution_actions",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_actions_status"),
        "execution_actions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claim_status", sa.String(length=32), nullable=False),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_outbox_events_decision_id_decisions"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_claim_ready",
        "outbox_events",
        ["claim_status", "available_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_available_at"),
        "outbox_events",
        ["available_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_claim_expires_at"),
        "outbox_events",
        ["claim_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_claim_status"),
        "outbox_events",
        ["claim_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_claimed_at"),
        "outbox_events",
        ["claimed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_claimed_by"),
        "outbox_events",
        ["claimed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_created_at"),
        "outbox_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_decision_id"),
        "outbox_events",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_event_type"),
        "outbox_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_processed_at"),
        "outbox_events",
        ["processed_at"],
        unique=False,
    )
    op.create_table(
        "playbacks",
        sa.Column("playback_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_instances.case_id"],
            name=op.f("fk_playbacks_case_id_case_instances"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_playbacks_decision_id_decisions"),
        ),
        sa.PrimaryKeyConstraint("playback_id", name=op.f("pk_playbacks")),
    )
    op.create_index(
        op.f("ix_playbacks_case_id"), "playbacks", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_playbacks_completed_at"), "playbacks", ["completed_at"], unique=False
    )
    op.create_index(
        op.f("ix_playbacks_decision_id"), "playbacks", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_playbacks_started_at"), "playbacks", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_playbacks_status"), "playbacks", ["status"], unique=False)
    op.create_table(
        "action_projection",
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "current_attempt", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["execution_actions.action_id"],
            name=op.f("fk_action_projection_action_id_execution_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_action_projection_decision_id_decisions"),
        ),
        sa.PrimaryKeyConstraint("action_id", name=op.f("pk_action_projection")),
    )
    op.create_index(
        op.f("ix_action_projection_case_id"),
        "action_projection",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_projection_decision_id"),
        "action_projection",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_projection_status"),
        "action_projection",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_projection_updated_at"),
        "action_projection",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "draft_artifacts",
        sa.Column("artifact_id", sa.String(length=128), nullable=False),
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("artifact_kind", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["execution_actions.action_id"],
            name=op.f("fk_draft_artifacts_action_id_execution_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_draft_artifacts_decision_id_decisions"),
        ),
        sa.PrimaryKeyConstraint("artifact_id", name=op.f("pk_draft_artifacts")),
    )
    op.create_index(
        op.f("ix_draft_artifacts_action_id"),
        "draft_artifacts",
        ["action_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_draft_artifacts_artifact_kind"),
        "draft_artifacts",
        ["artifact_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_draft_artifacts_created_at"),
        "draft_artifacts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_draft_artifacts_decision_id"),
        "draft_artifacts",
        ["decision_id"],
        unique=False,
    )
    op.create_table(
        "execution_attempts",
        sa.Column("attempt_id", sa.String(length=128), nullable=False),
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["execution_actions.action_id"],
            name=op.f("fk_execution_attempts_action_id_execution_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_execution_attempts_decision_id_decisions"),
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("pk_execution_attempts")),
        sa.UniqueConstraint(
            "action_id", "attempt_number", name="uq_execution_attempt_action_number"
        ),
    )
    op.create_index(
        op.f("ix_execution_attempts_action_id"),
        "execution_attempts",
        ["action_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_attempts_completed_at"),
        "execution_attempts",
        ["completed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_attempts_decision_id"),
        "execution_attempts",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_attempts_started_at"),
        "execution_attempts",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_attempts_status"),
        "execution_attempts",
        ["status"],
        unique=False,
    )
    op.create_table(
        "execution_events",
        sa.Column("execution_event_id", sa.String(length=128), nullable=False),
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["execution_actions.action_id"],
            name=op.f("fk_execution_events_action_id_execution_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_execution_events_decision_id_decisions"),
        ),
        sa.PrimaryKeyConstraint("execution_event_id", name=op.f("pk_execution_events")),
    )
    op.create_index(
        op.f("ix_execution_events_action_id"),
        "execution_events",
        ["action_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_decision_id"),
        "execution_events",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_event_type"),
        "execution_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_events_occurred_at"),
        "execution_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_table(
        "outcome_observations",
        sa.Column("observation_id", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("playback_id", sa.String(length=128), nullable=True),
        sa.Column("observation_kind", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_instances.case_id"],
            name=op.f("fk_outcome_observations_case_id_case_instances"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
            name=op.f("fk_outcome_observations_decision_id_decisions"),
        ),
        sa.ForeignKeyConstraint(
            ["playback_id"],
            ["playbacks.playback_id"],
            name=op.f("fk_outcome_observations_playback_id_playbacks"),
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_outcome_observations")),
    )
    op.create_index(
        op.f("ix_outcome_observations_case_id"),
        "outcome_observations",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outcome_observations_decision_id"),
        "outcome_observations",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outcome_observations_observation_kind"),
        "outcome_observations",
        ["observation_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outcome_observations_observed_at"),
        "outcome_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outcome_observations_playback_id"),
        "outcome_observations",
        ["playback_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_outcome_observations_playback_id"), table_name="outcome_observations"
    )
    op.drop_index(
        op.f("ix_outcome_observations_observed_at"), table_name="outcome_observations"
    )
    op.drop_index(
        op.f("ix_outcome_observations_observation_kind"),
        table_name="outcome_observations",
    )
    op.drop_index(
        op.f("ix_outcome_observations_decision_id"), table_name="outcome_observations"
    )
    op.drop_index(
        op.f("ix_outcome_observations_case_id"), table_name="outcome_observations"
    )
    op.drop_table("outcome_observations")
    op.drop_index(
        op.f("ix_execution_events_occurred_at"), table_name="execution_events"
    )
    op.drop_index(op.f("ix_execution_events_event_type"), table_name="execution_events")
    op.drop_index(
        op.f("ix_execution_events_decision_id"), table_name="execution_events"
    )
    op.drop_index(op.f("ix_execution_events_action_id"), table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index(op.f("ix_execution_attempts_status"), table_name="execution_attempts")
    op.drop_index(
        op.f("ix_execution_attempts_started_at"), table_name="execution_attempts"
    )
    op.drop_index(
        op.f("ix_execution_attempts_decision_id"), table_name="execution_attempts"
    )
    op.drop_index(
        op.f("ix_execution_attempts_completed_at"), table_name="execution_attempts"
    )
    op.drop_index(
        op.f("ix_execution_attempts_action_id"), table_name="execution_attempts"
    )
    op.drop_table("execution_attempts")
    op.drop_index(op.f("ix_draft_artifacts_decision_id"), table_name="draft_artifacts")
    op.drop_index(op.f("ix_draft_artifacts_created_at"), table_name="draft_artifacts")
    op.drop_index(
        op.f("ix_draft_artifacts_artifact_kind"), table_name="draft_artifacts"
    )
    op.drop_index(op.f("ix_draft_artifacts_action_id"), table_name="draft_artifacts")
    op.drop_table("draft_artifacts")
    op.drop_index(
        op.f("ix_action_projection_updated_at"), table_name="action_projection"
    )
    op.drop_index(op.f("ix_action_projection_status"), table_name="action_projection")
    op.drop_index(
        op.f("ix_action_projection_decision_id"), table_name="action_projection"
    )
    op.drop_index(op.f("ix_action_projection_case_id"), table_name="action_projection")
    op.drop_table("action_projection")
    op.drop_index(op.f("ix_playbacks_status"), table_name="playbacks")
    op.drop_index(op.f("ix_playbacks_started_at"), table_name="playbacks")
    op.drop_index(op.f("ix_playbacks_decision_id"), table_name="playbacks")
    op.drop_index(op.f("ix_playbacks_completed_at"), table_name="playbacks")
    op.drop_index(op.f("ix_playbacks_case_id"), table_name="playbacks")
    op.drop_table("playbacks")
    op.drop_index(op.f("ix_outbox_events_processed_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_event_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_decision_id"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_created_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_claimed_by"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_claimed_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_claim_status"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_claim_expires_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_available_at"), table_name="outbox_events")
    op.drop_index("ix_outbox_claim_ready", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_execution_actions_status"), table_name="execution_actions")
    op.drop_index(
        op.f("ix_execution_actions_decision_id"), table_name="execution_actions"
    )
    op.drop_index(
        op.f("ix_execution_actions_created_at"), table_name="execution_actions"
    )
    op.drop_index(op.f("ix_execution_actions_case_id"), table_name="execution_actions")
    op.drop_index(
        op.f("ix_execution_actions_action_kind"), table_name="execution_actions"
    )
    op.drop_table("execution_actions")
    op.drop_index(op.f("ix_case_projection_updated_at"), table_name="case_projection")
    op.drop_index(op.f("ix_case_projection_status"), table_name="case_projection")
    op.drop_index(
        op.f("ix_case_projection_scenario_effective_time"), table_name="case_projection"
    )
    op.drop_index(op.f("ix_case_projection_runtime_mode"), table_name="case_projection")
    op.drop_index("ix_case_projection_purpose_status", table_name="case_projection")
    op.drop_index(op.f("ix_case_projection_purpose"), table_name="case_projection")
    op.drop_index(
        op.f("ix_case_projection_current_decision_id"), table_name="case_projection"
    )
    op.drop_index(
        op.f("ix_case_projection_current_analysis_id"), table_name="case_projection"
    )
    op.drop_index(
        op.f("ix_case_projection_current_analysis_hash"), table_name="case_projection"
    )
    op.drop_table("case_projection")
    op.drop_index(
        op.f("ix_approval_satisfactions_satisfied"), table_name="approval_satisfactions"
    )
    op.drop_index(
        op.f("ix_approval_satisfactions_role"), table_name="approval_satisfactions"
    )
    op.drop_index(
        op.f("ix_approval_satisfactions_persona_id"),
        table_name="approval_satisfactions",
    )
    op.drop_index(
        op.f("ix_approval_satisfactions_option_id"), table_name="approval_satisfactions"
    )
    op.drop_index(
        op.f("ix_approval_satisfactions_decision_id"),
        table_name="approval_satisfactions",
    )
    op.drop_index(
        op.f("ix_approval_satisfactions_authorization_id"),
        table_name="approval_satisfactions",
    )
    op.drop_index(
        op.f("ix_approval_satisfactions_analysis_id"),
        table_name="approval_satisfactions",
    )
    op.drop_table("approval_satisfactions")
    op.drop_index(
        op.f("ix_evidence_items_source_timestamp"), table_name="evidence_items"
    )
    op.drop_index(op.f("ix_evidence_items_source_system"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_runtime_mode"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_retrieved_at"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_kind"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_expires_at"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_effective_at"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_case_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_decisions_runtime_mode"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_kind"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_decided_at"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_case_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_analysis_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(
        op.f("ix_operational_snapshots_scenario_effective_time"),
        table_name="operational_snapshots",
    )
    op.drop_index(
        op.f("ix_operational_snapshots_runtime_mode"),
        table_name="operational_snapshots",
    )
    op.drop_index(
        op.f("ix_operational_snapshots_analysis_horizon_start"),
        table_name="operational_snapshots",
    )
    op.drop_index(
        op.f("ix_operational_snapshots_analysis_horizon_end"),
        table_name="operational_snapshots",
    )
    op.drop_table("operational_snapshots")
    op.drop_index(
        op.f("ix_analysis_versions_runtime_mode"), table_name="analysis_versions"
    )
    op.drop_index(
        op.f("ix_analysis_versions_retrieval_window_ends_at"),
        table_name="analysis_versions",
    )
    op.drop_index(
        op.f("ix_analysis_versions_material_hash"), table_name="analysis_versions"
    )
    op.drop_index(
        op.f("ix_analysis_versions_created_at"), table_name="analysis_versions"
    )
    op.drop_index(op.f("ix_analysis_versions_case_id"), table_name="analysis_versions")
    op.drop_index(
        op.f("ix_analysis_versions_analysis_started_at"), table_name="analysis_versions"
    )
    op.drop_table("analysis_versions")
    op.drop_index(op.f("ix_case_instances_template_id"), table_name="case_instances")
    op.drop_index(op.f("ix_case_instances_status"), table_name="case_instances")
    op.drop_index(
        op.f("ix_case_instances_scenario_effective_time"), table_name="case_instances"
    )
    op.drop_index(op.f("ix_case_instances_runtime_mode"), table_name="case_instances")
    op.drop_index(op.f("ix_case_instances_recorded_at"), table_name="case_instances")
    op.drop_index(op.f("ix_case_instances_purpose"), table_name="case_instances")
    op.drop_table("case_instances")
    # ### end Alembic commands ###
