"""Deterministic exposure calculations for Supply Response.

No LLM is involved in any arithmetic in this module. Every function is pure and
reproducible: given the same inputs it always produces the same outputs.

Core formulas (from the project brief)::

    usable_inventory   = on_hand - quality_hold - protected_allocation

    projected_balance[date] = prior_balance
                            + confirmed_receipts
                            + approved_transfers
                            - component_demand
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
from typing import Iterable, Optional, Sequence

from pydantic import BaseModel, ConfigDict, Field

from data.schemas.models import (
    BomComponent,
    CustomerOrder,
    CustomerOrderStatus,
    InventoryPosition,
    POStatus,
    ProductionOrder,
    ProductionOrderStatus,
    PurchaseOrder,
)

CALCULATION_VERSION = "1.0.0"

_OPEN_PO_STATUSES = {POStatus.OPEN, POStatus.CONFIRMED, POStatus.PARTIAL, POStatus.DELAYED}
_OPEN_PRODUCTION_STATUSES = {
    ProductionOrderStatus.PLANNED,
    ProductionOrderStatus.RELEASED,
    ProductionOrderStatus.IN_PROGRESS,
}
_OPEN_CUSTOMER_STATUSES = {CustomerOrderStatus.OPEN, CustomerOrderStatus.ALLOCATED}


# --------------------------------------------------------------------------- #
# Result models
# --------------------------------------------------------------------------- #
class CalculationModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class Transfer(CalculationModel):
    """An approved inter-plant transfer of a part."""

    part_id: str
    to_plant_id: str
    from_plant_id: str = ""
    quantity: int = Field(ge=0)
    available_date: date


class DemandEvent(CalculationModel):
    """Component demand generated by a production order."""

    date: date
    quantity: int
    production_order_id: str
    part_id: str
    plant_id: str


class SupplyEvent(CalculationModel):
    """Confirmed receipt or approved transfer arriving on a date."""

    date: date
    quantity: int
    source_type: str  # "purchase_order" | "transfer"
    source_id: str


class BalanceRow(CalculationModel):
    date: date
    opening_balance: int
    confirmed_receipts: int
    approved_transfers: int
    component_demand: int
    projected_balance: int
    shortage: int


class AffectedProductionOrder(CalculationModel):
    production_order_id: str
    plant_id: str
    part_id: str  # the short component
    produced_part_id: str
    due_date: date
    required_qty: int
    shortage_qty: int
    lost_output_qty: int
    priority: int


class AffectedCustomerOrder(CalculationModel):
    customer_order_id: str
    order_line: int
    customer_id: str
    part_id: str
    plant_id: str
    promised_date: date
    quantity: int
    at_risk_qty: int
    revenue_at_risk: float
    margin_at_risk: float
    priority_tier: int = 2


class ExposureResult(CalculationModel):
    """Full exposure picture for one part / plant, with lineage."""

    scenario_id: str
    calculation_version: str = CALCULATION_VERSION
    calculated_at: datetime
    part_id: str
    plant_id: str
    horizon_start: date
    horizon_end: date
    usable_inventory: int
    balances: list[BalanceRow] = Field(default_factory=list)
    first_stockout_date: Optional[date] = None
    max_shortage_qty: int = 0
    total_shortage_qty: int = 0
    affected_production_orders: list[AffectedProductionOrder] = Field(default_factory=list)
    affected_customer_orders: list[AffectedCustomerOrder] = Field(default_factory=list)
    revenue_at_risk: float = 0.0
    margin_at_risk: float = 0.0
    otif_lines_at_risk: int = 0
    assumptions: list[str] = Field(default_factory=list)
    lineage: dict[str, list[str]] = Field(default_factory=dict)
    open_questions: list[str] = Field(default_factory=list)


# --------------------------------------------------------------------------- #
# Primitive calculations
# --------------------------------------------------------------------------- #
def usable_inventory(position: InventoryPosition) -> int:
    """usable = on_hand - quality_hold - protected_allocation (floored at zero)."""
    return max(position.on_hand - position.quality_hold - position.protected_allocation, 0)


def total_usable_inventory(
    positions: Iterable[InventoryPosition],
    part_id: str,
    plant_id: Optional[str] = None,
) -> int:
    return sum(
        usable_inventory(p)
        for p in positions
        if p.part_id == part_id and (plant_id is None or p.plant_id == plant_id)
    )


def confirmed_receipts(
    purchase_orders: Iterable[PurchaseOrder],
    part_id: str,
    plant_id: str,
    horizon_start: date,
    horizon_end: date,
) -> list[SupplyEvent]:
    """Open PO quantities landing inside the horizon, keyed on effective date.

    A delayed purchase order with no revised date contributes nothing: the
    system never invents a supplier commitment that does not exist.
    """
    events: list[SupplyEvent] = []
    for po in purchase_orders:
        if po.part_id != part_id or po.plant_id != plant_id:
            continue
        if po.status not in _OPEN_PO_STATUSES:
            continue
        if po.status == POStatus.DELAYED and po.revised_date is None:
            continue
        qty = po.open_qty
        if qty <= 0:
            continue
        receipt_date = po.effective_date
        if receipt_date < horizon_start or receipt_date > horizon_end:
            continue
        events.append(
            SupplyEvent(
                date=receipt_date,
                quantity=qty,
                source_type="purchase_order",
                source_id=f"{po.po_id}:{po.po_line}",
            )
        )
    return sorted(events, key=lambda e: (e.date, e.source_id))


def component_demand(
    production_orders: Iterable[ProductionOrder],
    bom_components: Sequence[BomComponent],
    part_id: str,
    plant_id: str,
    horizon_start: date,
    horizon_end: date,
) -> list[DemandEvent]:
    """Explode production orders into demand for ``part_id``.

    Demand is placed on the production order start date. Quantity per is scaled
    by the scrap factor and rounded up to whole units.
    """
    by_parent: dict[str, list[BomComponent]] = defaultdict(list)
    for comp in bom_components:
        if comp.component_part_id == part_id:
            by_parent[comp.parent_part_id].append(comp)

    events: list[DemandEvent] = []
    for order in production_orders:
        if order.plant_id != plant_id:
            continue
        if order.status not in _OPEN_PRODUCTION_STATUSES:
            continue
        if order.start_date < horizon_start or order.start_date > horizon_end:
            continue
        for comp in by_parent.get(order.part_id, []):
            gross = order.quantity * comp.qty_per / (1.0 - comp.scrap_factor)
            qty = int(gross) + (1 if gross > int(gross) else 0)
            if qty <= 0:
                continue
            events.append(
                DemandEvent(
                    date=order.start_date,
                    quantity=qty,
                    production_order_id=order.production_order_id,
                    part_id=part_id,
                    plant_id=plant_id,
                )
            )
    return sorted(events, key=lambda e: (e.date, e.production_order_id))


def project_balance(
    opening_balance: int,
    receipts: Sequence[SupplyEvent],
    transfers: Sequence[Transfer],
    demand: Sequence[DemandEvent],
    horizon_start: date,
    horizon_end: date,
) -> list[BalanceRow]:
    """Time-phase supply and demand into a daily projected balance.

    ``projected_balance = prior_balance + confirmed_receipts + approved_transfers
    - component_demand``. Balances may go negative; the negative amount is the
    shortage for that day.
    """
    if horizon_end < horizon_start:
        raise ValueError("horizon_end must not be before horizon_start")

    receipts_by_day: dict[date, int] = defaultdict(int)
    for event in receipts:
        receipts_by_day[event.date] += event.quantity

    transfers_by_day: dict[date, int] = defaultdict(int)
    for transfer in transfers:
        transfers_by_day[transfer.available_date] += transfer.quantity

    demand_by_day: dict[date, int] = defaultdict(int)
    for event in demand:
        demand_by_day[event.date] += event.quantity

    rows: list[BalanceRow] = []
    prior = opening_balance
    day = horizon_start
    while day <= horizon_end:
        receipt_qty = receipts_by_day.get(day, 0)
        transfer_qty = transfers_by_day.get(day, 0)
        demand_qty = demand_by_day.get(day, 0)
        projected = prior + receipt_qty + transfer_qty - demand_qty
        rows.append(
            BalanceRow(
                date=day,
                opening_balance=prior,
                confirmed_receipts=receipt_qty,
                approved_transfers=transfer_qty,
                component_demand=demand_qty,
                projected_balance=projected,
                shortage=max(-projected, 0),
            )
        )
        prior = projected
        day += timedelta(days=1)
    return rows


def first_stockout_date(rows: Sequence[BalanceRow]) -> Optional[date]:
    """The first date on which the projected balance is negative."""
    for row in rows:
        if row.projected_balance < 0:
            return row.date
    return None


def max_shortage_qty(rows: Sequence[BalanceRow]) -> int:
    """The largest single-day shortage across the horizon."""
    if not rows:
        return 0
    return max(row.shortage for row in rows)


def affected_production_orders(
    rows: Sequence[BalanceRow],
    demand: Sequence[DemandEvent],
    production_orders: Sequence[ProductionOrder],
) -> list[AffectedProductionOrder]:
    """Production orders that cannot be fully covered by projected supply.

    Component demand is allocated in date order against opening inventory plus
    receipts and transfers. Unlike ``project_balance`` (which carries a deficit
    forward), allocation never lends inventory it does not have, so a shortage
    on one order does not double count against later orders.

    ``lost_output_qty`` converts the component shortage back into finished
    units that cannot be produced, prorated against the order quantity.
    """
    if not rows:
        return []
    order_index = {o.production_order_id: o for o in production_orders}
    demand_by_day: dict[date, list[DemandEvent]] = defaultdict(list)
    for event in demand:
        demand_by_day[event.date].append(event)

    available = max(rows[0].opening_balance, 0)
    affected: list[AffectedProductionOrder] = []

    for row in rows:
        available += row.confirmed_receipts + row.approved_transfers
        for event in sorted(
            demand_by_day.get(row.date, []), key=lambda e: e.production_order_id
        ):
            covered = min(available, event.quantity)
            available -= covered
            shortage = event.quantity - covered
            if shortage <= 0:
                continue
            order = order_index.get(event.production_order_id)
            output_qty = order.quantity if order else 0
            lost_output = _ceil_div(output_qty * shortage, event.quantity) if event.quantity else 0
            affected.append(
                AffectedProductionOrder(
                    production_order_id=event.production_order_id,
                    plant_id=event.plant_id,
                    part_id=event.part_id,
                    produced_part_id=order.part_id if order else "",
                    due_date=order.due_date if order else event.date,
                    required_qty=event.quantity,
                    shortage_qty=shortage,
                    lost_output_qty=lost_output,
                    priority=order.priority if order else 3,
                )
            )
    return affected


def _ceil_div(numerator: int, denominator: int) -> int:
    if denominator == 0:
        return 0
    return -(-numerator // denominator)


def affected_customer_orders(
    affected_orders: Sequence[AffectedProductionOrder],
    production_orders: Sequence[ProductionOrder],
    customer_orders: Sequence[CustomerOrder],
    customer_priority: Optional[dict[str, int]] = None,
) -> list[AffectedCustomerOrder]:
    """Customer-order lines exposed by the lost production output.

    Lost finished-goods output is allocated to open customer-order lines for the
    same part and plant that are promised on or after the first missed
    production due date. The shortfall is absorbed by the least protected demand
    first: lowest customer priority tier, then latest promised date. A line can
    be partially at risk.
    """
    customer_priority = customer_priority or {}
    lost_by_key: dict[tuple[str, str], int] = defaultdict(int)
    first_due: dict[tuple[str, str], date] = {}

    for affected in affected_orders:
        if not affected.produced_part_id or affected.lost_output_qty <= 0:
            continue
        key = (affected.produced_part_id, affected.plant_id)
        lost_by_key[key] += affected.lost_output_qty
        if key not in first_due or affected.due_date < first_due[key]:
            first_due[key] = affected.due_date

    results: list[AffectedCustomerOrder] = []
    for key in sorted(lost_by_key):
        part_id, plant_id = key
        remaining = lost_by_key[key]
        cutoff = first_due[key]
        candidates = [
            order
            for order in customer_orders
            if order.status in _OPEN_CUSTOMER_STATUSES
            and order.part_id == part_id
            and order.plant_id == plant_id
            and order.promised_date >= cutoff
        ]
        candidates.sort(
            key=lambda o: (
                customer_priority.get(o.customer_id, 2),
                o.promised_date,
                o.customer_order_id,
                o.order_line,
            ),
            reverse=True,
        )
        for order in candidates:
            if remaining <= 0:
                break
            at_risk_qty = min(order.quantity, remaining)
            remaining -= at_risk_qty
            results.append(
                AffectedCustomerOrder(
                    customer_order_id=order.customer_order_id,
                    order_line=order.order_line,
                    customer_id=order.customer_id,
                    part_id=order.part_id,
                    plant_id=order.plant_id,
                    promised_date=order.promised_date,
                    quantity=order.quantity,
                    at_risk_qty=at_risk_qty,
                    revenue_at_risk=round(at_risk_qty * order.unit_price, 2),
                    margin_at_risk=round(at_risk_qty * (order.unit_price - order.unit_cost), 2),
                    priority_tier=customer_priority.get(order.customer_id, 2),
                )
            )
    results.sort(key=lambda o: (o.promised_date, o.customer_order_id, o.order_line))
    return results



def revenue_at_risk(orders: Sequence[AffectedCustomerOrder]) -> float:
    return round(sum(o.revenue_at_risk for o in orders), 2)


def margin_at_risk(orders: Sequence[AffectedCustomerOrder]) -> float:
    return round(sum(o.margin_at_risk for o in orders), 2)


def otif_lines_at_risk(orders: Sequence[AffectedCustomerOrder]) -> int:
    return len(orders)


def response_cost(
    expedite_qty: int = 0,
    expedite_cost_per_unit: float = 0.0,
    expedite_fixed_cost: float = 0.0,
    transfer_qty: int = 0,
    transfer_cost_per_unit: float = 0.0,
    transfer_fixed_cost: float = 0.0,
    resequencing_cost: float = 0.0,
    penalty_cost: float = 0.0,
) -> float:
    """Total incremental cost of executing a response."""
    total = (
        expedite_qty * expedite_cost_per_unit
        + (expedite_fixed_cost if expedite_qty > 0 else 0.0)
        + transfer_qty * transfer_cost_per_unit
        + (transfer_fixed_cost if transfer_qty > 0 else 0.0)
        + resequencing_cost
        + penalty_cost
    )
    return round(total, 2)


def revenue_protected(baseline_revenue_at_risk: float, scenario_revenue_at_risk: float) -> float:
    """Revenue rescued relative to doing nothing (never negative)."""
    return round(max(baseline_revenue_at_risk - scenario_revenue_at_risk, 0.0), 2)


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
def calculate_exposure(
    *,
    scenario_id: str,
    part_id: str,
    plant_id: str,
    horizon_start: date,
    horizon_end: date,
    inventory_positions: Sequence[InventoryPosition],
    purchase_orders: Sequence[PurchaseOrder],
    production_orders: Sequence[ProductionOrder],
    bom_components: Sequence[BomComponent],
    customer_orders: Sequence[CustomerOrder],
    transfers: Sequence[Transfer] = (),
    extra_receipts: Sequence[SupplyEvent] = (),
    customer_priority: Optional[dict[str, int]] = None,
    assumptions: Optional[Sequence[str]] = None,
    open_questions: Optional[Sequence[str]] = None,
    calculated_at: Optional[datetime] = None,
) -> ExposureResult:
    """Run the full deterministic exposure calculation for one part / plant."""
    opening = total_usable_inventory(inventory_positions, part_id, plant_id)
    receipts = confirmed_receipts(
        purchase_orders, part_id, plant_id, horizon_start, horizon_end
    )
    receipts += [
        event
        for event in extra_receipts
        if horizon_start <= event.date <= horizon_end and event.quantity > 0
    ]
    receipts.sort(key=lambda e: (e.date, e.source_id))
    demand = component_demand(
        production_orders, bom_components, part_id, plant_id, horizon_start, horizon_end
    )
    applicable_transfers = [
        t
        for t in transfers
        if t.part_id == part_id
        and t.to_plant_id == plant_id
        and horizon_start <= t.available_date <= horizon_end
    ]
    rows = project_balance(
        opening, receipts, applicable_transfers, demand, horizon_start, horizon_end
    )
    short_production = affected_production_orders(rows, demand, production_orders)
    short_customers = affected_customer_orders(
        short_production, production_orders, customer_orders, customer_priority
    )

    return ExposureResult(
        scenario_id=scenario_id,
        calculated_at=calculated_at or datetime.now(timezone.utc),
        part_id=part_id,
        plant_id=plant_id,
        horizon_start=horizon_start,
        horizon_end=horizon_end,
        usable_inventory=opening,
        balances=rows,
        first_stockout_date=first_stockout_date(rows),
        max_shortage_qty=max_shortage_qty(rows),
        total_shortage_qty=sum(o.shortage_qty for o in short_production),
        affected_production_orders=short_production,
        affected_customer_orders=short_customers,
        revenue_at_risk=revenue_at_risk(short_customers),
        margin_at_risk=margin_at_risk(short_customers),
        otif_lines_at_risk=otif_lines_at_risk(short_customers),
        assumptions=list(assumptions or []),
        open_questions=list(open_questions or []),
        lineage={
            "inventory_positions": [
                p.inventory_id
                for p in inventory_positions
                if p.part_id == part_id and p.plant_id == plant_id
            ],
            "purchase_orders": [e.source_id for e in receipts],
            "production_orders": sorted({e.production_order_id for e in demand}),
            "transfers": [f"{t.from_plant_id}->{t.to_plant_id}:{t.quantity}" for t in applicable_transfers],
            "customer_orders": [
                f"{o.customer_order_id}:{o.order_line}" for o in short_customers
            ],
        },
    )


__all__ = [
    "CALCULATION_VERSION",
    "AffectedCustomerOrder",
    "AffectedProductionOrder",
    "BalanceRow",
    "DemandEvent",
    "ExposureResult",
    "SupplyEvent",
    "Transfer",
    "affected_customer_orders",
    "affected_production_orders",
    "calculate_exposure",
    "component_demand",
    "confirmed_receipts",
    "first_stockout_date",
    "margin_at_risk",
    "max_shortage_qty",
    "otif_lines_at_risk",
    "project_balance",
    "response_cost",
    "revenue_at_risk",
    "revenue_protected",
    "total_usable_inventory",
    "usable_inventory",
]
