# Generated by python -m fabric.report_contract; do not edit the digest.
# This identifies local artifacts, not a deployed or available report.
REPORTING_CONTRACT = "saved-analysis-v1"
REPORTING_ARTIFACT_SHA256 = (
    "f8b94cd7dfab66430e17f537dcea3df3d52f40258ee2847eb601156da74fb485"
)
