# Generated by python -m fabric.report_contract; do not edit the digest.
# This identifies local artifacts, not a deployed or available report.
REPORTING_CONTRACT = "saved-analysis-v1"
REPORTING_ARTIFACT_SHA256 = (
    "00ed9d955f1e929eefc693a6df57e4ee50ff1261dca38a5be47f1da8c1393eae"
)
