# Generated by python -m fabric.report_contract; do not edit the digest.
# This identifies local artifacts, not a deployed or available report.
REPORTING_CONTRACT = "saved-analysis-v1"
REPORTING_ARTIFACT_SHA256 = (
    "fabf4860f00af21c53030a48c119b632e2ed567b4d594fe784c72ec9b8373190"
)
